services:
  - type: web
    name: sector-analytics-recorder
    env: docker
    plan: free
    buildCommand: ""
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 5001
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1 